### ISSUE TITLE
hex?

### ISSUE THREAD

**Issue by hasnogaems** [ath31st/s21_decimal_starter#1]
Почему результат в hex, сложно же сказать правильно или нет у тебя глядя на hex или ожидается что мы напишем функцию принтующую в hex?

**Comment by ath31st** [comment]
Причина простая - hex наиболее короткий, а значит и более удобный и наглядный формат.
Выбор стоит между двоичной, шестнадцатеричной, десятичной. В двоичной системе ансайнед инт это 32 нуля и единицы, от которых будет рябить в глазах и понятнее не станет.  Разницу между десятичной и шестнадцатеричной можно увидеть на скриншоте. Введенное число и так и так не опознать в разложенном на 4 инта виде, но в хексе более читаемо - нет знаков, например.
![screen_00333](https://github.com/ath31st/s21_decimal_starter/assets/31596688/a5b17e3c-92fc-45e5-a367-ae4e2b8c8a90)

На счет последнего - принтующая функция в проекте если и нужна, то только для собственной наглядности, если в дебаггере не можешь/не хочешь смотреть промежуточные результаты.
А вообще, для этого и был создан этот стартер, чтобы было проще перегонять туда и обратно значения. Когда я делал проект, мне приходилось много времени тратить в онлайн конвертерах по частям перегоняя куски децималов, чтобы понять - хоть примерно похоже на то, что мне надо или нет.

**Comment by hasnogaems** [comment]
Это же clion? Ты бываешь в кампусе? Очень нужно менторство для вката в clion.

**Comment by ath31st** [comment]
это другая ide, но тоже от jet brains. в кампусе бываю редко. если же речь идет о дебаггере, то он и в vs code есть.

**Comment by hasnogaems** [comment]
![image](https://github.com/ath31st/s21_decimal_starter/assets/14231492/cc47413c-69a9-4884-8476-373ca169d84e)
Подскажи почему тут скобки два раза? И что за ide? Она норм для C и С++? Лучше чем vscode? В vscode если баг возникает в тесте дебаггером не зайти, он будто выполняется в какой-то отдельной среде которую дебаггер не видит, на каких ide можно зайти?

**Comment by ath31st** [comment]
Скобки два раза. Первые для структуры s21_decimal, а вторые уже для внутреннего массива (тот что bits).
На счёт ide - intellij idea. Проект написан на java и это ide для этого языка программирования. Естественно, для c/c++ она не подойдёт.
Теперь про дебаггер. Что в vs code, что в clion он вполне работает. Если у тебя в брейк поинтах выполнение кода не останавливается, то, скорее всего, ты компилируешь проект без флага -g, который отвечает за добавление отладочной информации в файлы.
Более того, дебажить можно и без ide, прямо в консоли с помощью gdb, но это уже занятие не для начинающих.
Ну и ответы на все эти вопросы ты мог бы быстрее сам нагуглить, спросить у сокомандников или  в рокет чате или канале волны в телеге, чем ждать его здесь.
